### ISSUE TITLE
Parsing the time format returned by NiFi

### ISSUE THREAD

**Issue by Unkas** [simplesteph/nifi-api-client-java#1]
When doing a simple call to NiFi 1.3.0 such as:
`ProcessGroupFlowEntity result = flowApi.getFlow("root");`

I get the following exception:
Exception in thread "main" java.lang.IllegalArgumentException: Invalid format: "12:52:25 EDT" is malformed at ":52:25 EDT"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
	at io.swagger.client.DateTimeTypeAdapter.read(JSON.java:204)
	at io.swagger.client.DateTimeTypeAdapter.read(JSON.java:183)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at ...
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at io.swagger.client.JSON.deserialize(JSON.java:115)
	at io.swagger.client.ApiClient.deserialize(ApiClient.java:851)
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:1047)
	at io.swagger.client.ApiClient.execute(ApiClient.java:981)
	at io.swagger.client.api.FlowApi.getFlowWithHttpInfo(FlowApi.java:1723)
	at io.swagger.client.api.FlowApi.getFlow(FlowApi.java:1709)

It seems Joda does not parse just time strings with ':' within.  Is there a variable I can set to be able to parse the time in the NiFi response?

**Comment by Unkas** [comment]
Addressed in #2
